name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ master, develop, alpha ]
  pull_request:
    branches: [ master, develop, alpha ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Setup JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Write signing key
      run: |
        if [ ! -z "${{ secrets.SIGNING_KEY }}" ]; then
          echo STORE_PASSWORD='${{ secrets.KEY_STORE_PASSWORD }}' >> local.properties
          echo KEY_ALIAS='${{ secrets.ALIAS }}' >> local.properties
          echo KEY_PASSWORD='${{ secrets.KEY_PASSWORD }}' >> local.properties
          echo STORE_FILE_PATH='../release.keystore' >> local.properties
          echo ${{ secrets.SIGNING_KEY }} | base64 --decode > release.keystore
        fi

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Collect artifcat name
      run: |
        echo "release_artifact=$(basename -s .apk app/build/outputs/apk/release/*.apk)" >> $GITHUB_ENV

    - name: Upload to Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.release_artifact }}
        path: app/build/outputs/apk/release/*.apk
