name: Release CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Force fetch Tags
      run: |
        git fetch --tags --force

    - name: Get Tag
      id: var
      run: |
        echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        echo ::set-output name=version::${GITHUB_REF#refs/*/v}

    - name: Setup JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Write signing key
      run: |
        if [ ! -z "${{ secrets.SIGNING_KEY }}" ]; then
          echo STORE_PASSWORD='${{ secrets.KEY_STORE_PASSWORD }}' >> local.properties
          echo KEY_ALIAS='${{ secrets.ALIAS }}' >> local.properties
          echo KEY_PASSWORD='${{ secrets.KEY_PASSWORD }}' >> local.properties
          echo STORE_FILE_PATH='../release.keystore' >> local.properties
          echo ${{ secrets.SIGNING_KEY }} | base64 --decode > release.keystore
        fi

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Collect artifcat name
      run: |
        echo "release_artifact=$(basename -s .apk app/build/outputs/apk/release/*.apk)" >> $GITHUB_ENV

    - name: Upload to Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.release_artifact }}
        path: app/build/outputs/apk/release/*.apk

    - uses: ericcornelissen/git-tag-annotation-action@v2
      id: tag-data

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.var.outputs.tag }}
        body: ${{ steps.tag-data.outputs.git-tag-annotation }}
        artifacts: "app/build/outputs/apk/release/*.apk"
        allowUpdates: true
        removeArtifacts: true

